# Generated by Django 5.0.6 on 2024-06-02 17:06

import django.db.models.deletion
import recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ingredients_first", models.CharField(blank=True, max_length=500)),
                ("Ingredients_second", models.CharField(blank=True, max_length=500)),
                ("Ingredients_third", models.CharField(blank=True, max_length=500)),
                ("Ingredients_fourth", models.CharField(blank=True, max_length=500)),
                ("Ingredients_fifth", models.CharField(blank=True, max_length=500)),
                ("Ingredients_sixth", models.CharField(blank=True, max_length=500)),
                ("Ingredients_seventh", models.CharField(blank=True, max_length=500)),
                ("Ingredients_eigth", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=200)),
                (
                    "preference",
                    models.TextField(
                        blank=True,
                        default="",
                        validators=[recipe.models.Recipe.validate_max_words],
                    ),
                ),
                (
                    "dietaryRequirments",
                    models.TextField(
                        blank=True,
                        default="",
                        validators=[recipe.models.Recipe.validate_max_words],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("recipe", models.TextField(blank=True)),
                (
                    "ingredients",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recipe.ingredients",
                    ),
                ),
            ],
        ),
    ]
